config/routes.rb
Diamond::Application.routes.draw do
  devise_for :users
  root "rfps#new"

  get '/matches/new', controller: 'matches', action: 'new', as: 'new_match'
  post '/matches', controller: 'matches', action: 'create', as: 'matches'

  get '/matches', controller: 'matches', action: 'index'
  get '/matches/:id', controller: 'matches', action: 'show', as: 'match'

  get '/matches/:id/edit', controller: 'matches', action: 'edit', as: 'edit_match'
  patch '/matches/:id', controller: 'matches', action: 'update'

  delete '/matches/:id', controller: 'matches', action: 'destroy'

  get '/merchants/new', controller: 'merchants', action: 'new', as: 'new_merchant'
  post '/merchants', controller: 'merchants', action: 'create', as: 'merchants'

  get '/merchants', controller: 'merchants', action: 'index'
  get '/merchants/:id', controller: 'merchants', action: 'show', as: 'merchant'

  get '/merchants/:id/edit', controller: 'merchants', action: 'edit', as: 'edit_merchant'
  patch '/merchants/:id', controller: 'merchants', action: 'update'

  delete '/merchants/:id', controller: 'merchants', action: 'destroy'

  get '/users/new', controller: 'users', action: 'new', as: 'new_user'
  post '/users', controller: 'users', action: 'create', as: 'users'

  get '/users', controller: 'users', action: 'index'
  get '/users/:id', controller: 'users', action: 'show', as: 'user'

  get '/users/:id/edit', controller: 'users', action: 'edit', as: 'edit_user'
  patch '/users/:id', controller: 'users', action: 'update'

  delete '/users/:id', controller: 'users', action: 'destroy'

  get '/offers/new', controller: 'offers', action: 'new', as: 'new_offer'
  post '/offers', controller: 'offers', action: 'create', as: 'offers'

  get '/offers', controller: 'offers', action: 'index'
  get '/offers/:id', controller: 'offers', action: 'show', as: 'offer'

  get '/offers/:id/edit', controller: 'offers', action: 'edit', as: 'edit_offer'
  patch '/offers/:id', controller: 'offers', action: 'update'

  delete '/offers/:id', controller: 'offers', action: 'destroy'

  get '/rfps/new', controller: 'rfps', action: 'new', as: 'new_rfp'
  post '/rfps', controller: 'rfps', action: 'create', as: 'rfps'

  get '/rfps', controller: 'rfps', action: 'index'
  get '/rfps/:id', controller: 'rfps', action: 'show', as: 'rfp'

  get '/rfps/:id/edit', controller: 'rfps', action: 'edit', as: 'edit_rfp'
  patch '/rfps/:id', controller: 'rfps', action: 'update'

  delete '/rfps/:id', controller: 'rfps', action: 'destroy'

end

app/models/merchant.rb
class Merchant < ActiveRecord::Base
  has_many :offers, :dependent => :destroy
  has_many :matches, :dependent => :destroy

validates :business_name, :presence => true
validates :address, :presence => true
validates :city, :presence => true
validates :state, :presence => true
validates :zip_code, :presence => true, numericality: { only_integer: true }, length: { is: 5 }
validates :email, :presence => true
validates :phone_number, :presence => true

end

app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController

  def index
    @merchants = Merchant.all
  end

  def show
    @merchant = Merchant.find_by(id: params[:id])
  end

  def new
    @merchant = Merchant.new
  end

  def create
    @merchant = Merchant.new
    @merchant.business_name = params[:business_name]
    @merchant.address = params[:address]
    @merchant.city = params[:city]
    @merchant.state = params[:state]
    @merchant.zip_code = params[:zip_code]
    @merchant.email = params[:email]
    @merchant.phone_number = params[:phone_number]
    @merchant.image_url = params[:image_url]

    if @merchant.save
      redirect_to merchants_url, notice: "Merchant created successfully."
    else
      render 'new'
    end
  end

  def edit
    @merchant = Merchant.find_by(id: params[:id])
  end

  def update
    @merchant = Merchant.find_by(id: params[:id])
    @merchant.business_name = params[:business_name]
    @merchant.address = params[:address]
    @merchant.city = params[:city]
    @merchant.state = params[:state]
    @merchant.zip_code = params[:zip_code]
    @merchant.email = params[:email]
    @merchant.phone_number = params[:phone_number]
    @merchant.image_url = params[:image_url]

    if @merchant.save
      redirect_to merchants_url, notice: "Merchant updated successfully."
    else
      render 'edit'
    end
  end

  def destroy
    @merchant = Merchant.find_by(id: params[:id])
    @merchant.destroy

    redirect_to merchants_url, notice: "Merchant deleted."
  end
end

app/views/merchants/edit.html.erb
<div class="page-header">
  <h1>Editing Merchant #<%= @merchant.id %></h1>
</div>

<% if @merchant.errors.any? %>
    <% @merchant.errors.full_messages.each do |message| %>
        <div class="alert alert-dismissable alert-danger">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= message %>
      </div>
    <% end %>
<% end  %>

<%= form_tag(merchant_url(@merchant), method: 'patch', class: 'form-horizontal') do %>
  <div class="form-group">
    <%= label_tag :business_name, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :business_name, @merchant.business_name, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :address, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :address, @merchant.address, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :city, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :city, @merchant.city, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :state, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :state, @merchant.state, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :zip_code, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :zip_code, @merchant.zip_code, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :email, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :email, @merchant.email, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :phone_number, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :phone_number, @merchant.phone_number, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :image_url, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :image_url, @merchant.image_url, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
      <%= submit_tag "Update Merchant", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/merchants/index.html.erb
<div class="page-header">
  <h1>Merchants</h1>
</div>

<p><%= link_to 'Add a New Merchant', new_merchant_url, class: 'btn btn-primary' %></p>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Business name</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Zip code</th>
      <th>Email</th>
      <th>Phone number</th>
      <th>Image</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @merchants.each do |merchant| %>
      <tr>
        <td><%= merchant.business_name %></td>
        <td><%= merchant.address %></td>
        <td><%= merchant.city %></td>
        <td><%= merchant.state %></td>
        <td><%= merchant.zip_code %></td>
        <td><%= merchant.email %></td>
        <td><%= merchant.phone_number %></td>
        <td><%= image_tag merchant.image_url, width: 200 %></td>
        <td><%= link_to '<i class="fa fa-search-plus"></i>'.html_safe, merchant_url(merchant), class: 'btn btn-primary' %></td>
        <td><%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_merchant_url(merchant), class: 'btn btn-warning' %></td>
        <td><%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, merchant_url(merchant), method: 'delete', data: { confirm: "Do you really want to delete this merchant?" }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/merchants/new.html.erb
<div class="page-header">
  <h1>New Merchant</h1>
</div>

<% if @merchant.errors.any? %>
    <% @merchant.errors.full_messages.each do |message| %>
        <div class="alert alert-dismissable alert-danger">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= message %>
      </div>
    <% end %>
<% end  %>

<%= form_tag(merchants_url, method: 'post', class: 'form-horizontal') do %>
  <div class="form-group">
    <%= label_tag :business_name, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :business_name, @merchant.business_name , class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :address, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :address, @merchant.address , class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :city, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :city, @merchant.city , class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :state, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :state, @merchant.state , class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :zip_code, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :zip_code, @merchant.zip_code , class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :email, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :email, @merchant.email , class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :phone_number, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :phone_number, @merchant.phone_number , class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :image_url, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :image_url, @merchant.image_url , class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
      <%= submit_tag "Create Merchant", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/merchants/show.html.erb
<div class="page-header">
  <h1><%= @merchant.business_name %></h1>
</div>

<dl class="dl-horizontal">

  <dt>Address</dt>
  <dd><%= @merchant.address %></dd>

  <dt>City</dt>
  <dd><%= @merchant.city %></dd>

  <dt>State</dt>
  <dd><%= @merchant.state %></dd>

  <dt>Zip code</dt>
  <dd><%= @merchant.zip_code %></dd>

  <dt>Email</dt>
  <dd><%= @merchant.email %></dd>

  <dt>Phone number</dt>
  <dd><%= @merchant.phone_number %></dd>

  <dt>Image</dt>
  <dd><%= image_tag @merchant.image_url, width: 200 %></dd>

</dl>

<div>
<dt>Requests Matched to You</dt>
<% @merchant.matches.each do |match| %>
  <li><%= match.rfp.full_diamond_trait %></li>
<% end %>
</div>

<div>
<dt>Offers You've Made</dt>
<% @merchant.offers.each do |offer| %>
  <li><%= offer.full_diamond_trait %></li>
<% end %>
</div>