config/routes.rb
Diamond::Application.routes.draw do
  devise_for :users
  root "rfps#new"

  get '/matches/new', controller: 'matches', action: 'new', as: 'new_match'
  post '/matches', controller: 'matches', action: 'create', as: 'matches'

  get '/matches', controller: 'matches', action: 'index'
  get '/matches/:id', controller: 'matches', action: 'show', as: 'match'

  get '/matches/:id/edit', controller: 'matches', action: 'edit', as: 'edit_match'
  patch '/matches/:id', controller: 'matches', action: 'update'

  delete '/matches/:id', controller: 'matches', action: 'destroy'

  get '/merchants/new', controller: 'merchants', action: 'new', as: 'new_merchant'
  post '/merchants', controller: 'merchants', action: 'create', as: 'merchants'

  get '/merchants', controller: 'merchants', action: 'index'
  get '/merchants/:id', controller: 'merchants', action: 'show', as: 'merchant'

  get '/merchants/:id/edit', controller: 'merchants', action: 'edit', as: 'edit_merchant'
  patch '/merchants/:id', controller: 'merchants', action: 'update'

  delete '/merchants/:id', controller: 'merchants', action: 'destroy'

  get '/users/new', controller: 'users', action: 'new', as: 'new_user'
  post '/users', controller: 'users', action: 'create', as: 'users'

  get '/users', controller: 'users', action: 'index'
  get '/users/:id', controller: 'users', action: 'show', as: 'user'

  get '/users/:id/edit', controller: 'users', action: 'edit', as: 'edit_user'
  patch '/users/:id', controller: 'users', action: 'update'

  delete '/users/:id', controller: 'users', action: 'destroy'

  get '/offers/new', controller: 'offers', action: 'new', as: 'new_offer'
  post '/offers', controller: 'offers', action: 'create', as: 'offers'

  get '/offers', controller: 'offers', action: 'index'
  get '/offers/:id', controller: 'offers', action: 'show', as: 'offer'

  get '/offers/:id/edit', controller: 'offers', action: 'edit', as: 'edit_offer'
  patch '/offers/:id', controller: 'offers', action: 'update'

  delete '/offers/:id', controller: 'offers', action: 'destroy'

  get '/rfps/new', controller: 'rfps', action: 'new', as: 'new_rfp'
  post '/rfps', controller: 'rfps', action: 'create', as: 'rfps'

  get '/rfps', controller: 'rfps', action: 'index'
  get '/rfps/:id', controller: 'rfps', action: 'show', as: 'rfp'

  get '/rfps/:id/edit', controller: 'rfps', action: 'edit', as: 'edit_rfp'
  patch '/rfps/:id', controller: 'rfps', action: 'update'

  delete '/rfps/:id', controller: 'rfps', action: 'destroy'

end

app/models/match.rb
class Match < ActiveRecord::Base
  belongs_to :rfp
  belongs_to :merchant

  validates :rfp, :presence => true
  validates :merchant, :presence => true

  def full_diamond_trait
    return "#{max_price}  #{carat}  #{shape} #{color}  #{cut}  #{clarity}"
  end

end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController

  def index
    @matches = Match.all
  end

  def show
    @match = Match.find_by(id: params[:id])
  end

  def new
    @match = Match.new
  end

  def create
    @match = Match.new
    @match.merchant_id = params[:merchant_id]
    @match.rfp_id = params[:rfp_id]

    if @match.save
      redirect_to matches_url, notice: "Match created successfully."
    else
      render 'new'
    end
  end

  def edit
    @match = Match.find_by(id: params[:id])
  end

  def update
    @match = Match.find_by(id: params[:id])
    @match.merchant_id = params[:merchant_id]
    @match.rfp_id = params[:rfp_id]

    if @match.save
      redirect_to matches_url, notice: "Match updated successfully."
    else
      render 'edit'
    end
  end

  def destroy
    @match = Match.find_by(id: params[:id])
    @match.destroy

    redirect_to matches_url, notice: "Match deleted."
  end
end

app/views/matches/edit.html.erb
<div class="page-header">
  <h1>Editing Match #<%= @match.id %></h1>
</div>

<% if @match.errors.any? %>
    <% @match.errors.full_messages.each do |message| %>
        <div class="alert alert-dismissable alert-danger">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= message %>
      </div>
    <% end %>
<% end  %>

<%= form_tag(match_url(@match), method: 'patch', class: 'form-horizontal') do %>
  <div class="form-group">
    <%= label_tag :merchant_id, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= select_tag :merchant_id, options_from_collection_for_select(Merchant.all, :id, :business_name), class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :rfp_id, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= select_tag :rfp_id, options_from_collection_for_select(Rfp.all, :id, :full_diamond_trait), class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
      <%= submit_tag "Update Match", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/matches/index.html.erb
<div class="page-header">
  <h1>Matches</h1>
</div>

<p><%= link_to 'Add a New Match', new_match_url, class: 'btn btn-primary' %></p>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Merchant</th>
      <th>Rfp</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @matches.each do |match| %>
      <tr>
        <td><%= match.merchant.business_name %></td>
        <td><%= match.rfp.full_diamond_trait %></td>
        <td><%= link_to '<i class="fa fa-search-plus"></i>'.html_safe, match_url(match), class: 'btn btn-primary' %></td>
        <td><%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_match_url(match), class: 'btn btn-warning' %></td>
        <td><%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, match_url(match), method: 'delete', data: { confirm: "Do you really want to delete this match?" }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/matches/new.html.erb
<div class="page-header">
  <h1>New Match</h1>
</div>

<% if @match.errors.any? %>
    <% @match.errors.full_messages.each do |message| %>
        <div class="alert alert-dismissable alert-danger">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= message %>
      </div>
    <% end %>
<% end  %>

<%= form_tag(matches_url, method: 'post', class: 'form-horizontal') do %>
  <div class="form-group">
    <%= label_tag :merchant_id, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
    <%= select_tag :merchant_id, options_from_collection_for_select(Merchant.all, :id, :business_name), class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :rfp_id, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
    <%= select_tag :rfp_id, options_from_collection_for_select(Rfp.all, :id, :full_diamond_trait), class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
      <%= submit_tag "Create Match", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/matches/show.html.erb
<div class="page-header">
  <h1>Match #<%= @match.id %></h1>
</div>

<dl class="dl-horizontal">
  <dt>Merchant</dt>
  <dd><%= @match.merchant.business_name %></dd>

  <dt>Rfp</dt>
  <dd><%= @match.rfp.full_diamond_trait %></dd>

</dl>