config/routes.rb
Diamond::Application.routes.draw do
  devise_for :users
  root "rfps#new"

  get '/matches/new', controller: 'matches', action: 'new', as: 'new_match'
  post '/matches', controller: 'matches', action: 'create', as: 'matches'

  get '/matches', controller: 'matches', action: 'index'
  get '/matches/:id', controller: 'matches', action: 'show', as: 'match'

  get '/matches/:id/edit', controller: 'matches', action: 'edit', as: 'edit_match'
  patch '/matches/:id', controller: 'matches', action: 'update'

  delete '/matches/:id', controller: 'matches', action: 'destroy'

  get '/merchants/new', controller: 'merchants', action: 'new', as: 'new_merchant'
  post '/merchants', controller: 'merchants', action: 'create', as: 'merchants'

  get '/merchants', controller: 'merchants', action: 'index'
  get '/merchants/:id', controller: 'merchants', action: 'show', as: 'merchant'

  get '/merchants/:id/edit', controller: 'merchants', action: 'edit', as: 'edit_merchant'
  patch '/merchants/:id', controller: 'merchants', action: 'update'

  delete '/merchants/:id', controller: 'merchants', action: 'destroy'

  get '/users/new', controller: 'users', action: 'new', as: 'new_user'
  post '/users', controller: 'users', action: 'create', as: 'users'

  get '/users', controller: 'users', action: 'index'
  get '/users/:id', controller: 'users', action: 'show', as: 'user'

  get '/users/:id/edit', controller: 'users', action: 'edit', as: 'edit_user'
  patch '/users/:id', controller: 'users', action: 'update'

  delete '/users/:id', controller: 'users', action: 'destroy'

  get '/offers/new', controller: 'offers', action: 'new', as: 'new_offer'
  post '/offers', controller: 'offers', action: 'create', as: 'offers'

  get '/offers', controller: 'offers', action: 'index'
  get '/offers/:id', controller: 'offers', action: 'show', as: 'offer'

  get '/offers/:id/edit', controller: 'offers', action: 'edit', as: 'edit_offer'
  patch '/offers/:id', controller: 'offers', action: 'update'

  delete '/offers/:id', controller: 'offers', action: 'destroy'

  get '/rfps/new', controller: 'rfps', action: 'new', as: 'new_rfp'
  post '/rfps', controller: 'rfps', action: 'create', as: 'rfps'

  get '/rfps', controller: 'rfps', action: 'index'
  get '/rfps/:id', controller: 'rfps', action: 'show', as: 'rfp'

  get '/rfps/:id/edit', controller: 'rfps', action: 'edit', as: 'edit_rfp'
  patch '/rfps/:id', controller: 'rfps', action: 'update'

  delete '/rfps/:id', controller: 'rfps', action: 'destroy'

end

app/models/offer.rb
class Offer < ActiveRecord::Base
  belongs_to :merchant
  belongs_to :rfp
  belongs_to :user

  def full_diamond_trait
    return "#{price}  #{carat}  #{shape} #{color}  #{cut}  #{clarity}"
  end

def user
  return User.find(user_id)
end

def merchant
  return Merchant.find(merchant_id)
end

def rfp
  return Rfp.find(rfp_id)
end

  validates :price, numericality: { greater_than: 0 }
  validates :shape, :presence => true
  validates :cut, :presence => true
  validates :color, :presence => true
  validates :clarity, :presence => true
  validates :carat, numericality: { greater_than: 0 }
  validates :user_id, :presence => true
  validates :merchant_id, :presence => true
  validates :rfp_id, :presence => true

end

app/controllers/offers_controller.rb
class OffersController < ApplicationController

  def index
    @offers = current_user.offers
  end

  def show
    @offer = Offer.find_by(id: params[:id])
  end

  def new
    @offer = Offer.new
  end

  def create
    @offer = Offer.new
    @offer.price = params[:price]
    @offer.shape = params[:shape]
    @offer.cut = params[:cut]
    @offer.color = params[:color]
    @offer.clarity = params[:clarity]
    @offer.carat = params[:carat]
    @offer.comment = params[:comment]
    @offer.user_id = current_user.id
    @offer.merchant_id = params[:merchant_id]
    @offer.rfp_id = params[:rfp_id]

    if @offer.save
      redirect_to offers_url, notice: "Offer created successfully."
    else
      render 'new'
    end
  end

  def edit
    @offer = Offer.find_by(id: params[:id])
  end

  def update
    @offer = Offer.find_by(id: params[:id])
    @offer.price = params[:price]
    @offer.shape = params[:shape]
    @offer.cut = params[:cut]
    @offer.color = params[:color]
    @offer.clarity = params[:clarity]
    @offer.carat = params[:carat]
    @offer.comment = params[:comment]
    @offer.user_id = current_user.id
    @offer.merchant_id = params[:merchant_id]
    @offer.rfp_id = params[:rfp_id]

    if @offer.save
      redirect_to offers_url, notice: "Offer updated successfully."
    else
      render 'edit'
    end
  end

  def destroy
    @offer = Offer.find_by(id: params[:id])
    @offer.destroy

    redirect_to offers_url, notice: "Offer deleted."
  end
end

app/views/offers/edit.html.erb
<div class="page-header">
  <h1>Editing Offer #<%= @offer.id %></h1>
</div>

<% if @offer.errors.any? %>
    <% @offer.errors.full_messages.each do |message| %>
        <div class="alert alert-dismissable alert-danger">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= message %>
      </div>
    <% end %>
<% end  %>

<%= form_tag(offer_url(@offer), method: 'patch', class: 'form-horizontal') do %>
  <div class="form-group">
    <%= label_tag :price, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :price, @offer.price, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :shape, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :shape, @offer.shape, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :cut, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :cut, @offer.cut, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :color, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :color, @offer.color, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :clarity, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :clarity, @offer.clarity, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :carat, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :carat, @offer.carat, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :comment, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_area_tag :comment, @offer.comment, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :merchant_id, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= select_tag :merchant_id, options_from_collection_for_select(Merchant.all, :id, :business_name), class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :rfp_id, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= select_tag :rfp_id, options_from_collection_for_select(Rfp.all, :id, :full_diamond_trait), class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
      <%= submit_tag "Update Offer", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/offers/index.html.erb
<div class="page-header">
  <h1>Offers</h1>
</div>

<p><%= link_to 'Add a New Offer', new_offer_url, class: 'btn btn-primary' %></p>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Price</th>
      <th>Shape</th>
      <th>Cut</th>
      <th>Color</th>
      <th>Clarity</th>
      <th>Carat</th>
      <th>Comment</th>
      <th>User</th>
      <th>Merchant</th>
      <th>Rfp</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @offers.each do |offer| %>
      <tr>
        <td><%= offer.price %></td>
        <td><%= offer.shape %></td>
        <td><%= offer.cut %></td>
        <td><%= offer.color %></td>
        <td><%= offer.clarity %></td>
        <td><%= offer.carat %></td>
        <td><%= offer.comment %></td>
        <td><%= offer.user.full_name %></td>
        <td><%= offer.merchant.business_name %></td>
        <td><%= offer.rfp.full_diamond_trait %></td>
        <td><%= link_to '<i class="fa fa-search-plus"></i>'.html_safe, offer_url(offer), class: 'btn btn-primary' %></td>
        <td><%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_offer_url(offer), class: 'btn btn-warning' %></td>
        <td><%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, offer_url(offer), method: 'delete', data: { confirm: "Do you really want to delete this offer?" }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/offers/new.html.erb
<div class="page-header">
  <h1>New Offer</h1>
</div>

<% if @offer.errors.any? %>
    <% @offer.errors.full_messages.each do |message| %>
        <div class="alert alert-dismissable alert-danger">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= message %>
      </div>
    <% end %>
<% end  %>

<%= form_tag(offers_url, method: 'post', class: 'form-horizontal') do %>
  <div class="form-group">
    <%= label_tag :price, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :price, @offer.price , class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :shape, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :shape, @offer.shape , class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :cut, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :cut, @offer.cut , class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :color, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :color, @offer.color , class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :clarity, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :clarity, @offer.clarity , class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :carat, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :carat, @offer.carat , class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :comment, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_area_tag :comment, @offer.comment , class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :merchant_id, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= select_tag :merchant_id, options_from_collection_for_select(Merchant.all, :id, :business_name), class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :rfp_id, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= select_tag :rfp_id, options_from_collection_for_select(Rfp.all, :id, :full_diamond_trait), class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
      <%= submit_tag "Create Offer", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/offers/show.html.erb
<div class="page-header">
  <h1>Offer #<%= @offer.id %></h1>
</div>

<dl class="dl-horizontal">
  <dt>Price</dt>
  <dd><%= @offer.price %></dd>

  <dt>Shape</dt>
  <dd><%= @offer.shape %></dd>

  <dt>Cut</dt>
  <dd><%= @offer.cut %></dd>

  <dt>Color</dt>
  <dd><%= @offer.color %></dd>

  <dt>Clarity</dt>
  <dd><%= @offer.clarity %></dd>

  <dt>Carat</dt>
  <dd><%= @offer.carat %></dd>

  <dt>Comment</dt>
  <dd><%= @offer.comment %></dd>

  <dt>User</dt>
  <dd><%= @offer.user.full_name %></dd>

  <dt>Merchant</dt>
  <dd><%= @offer.merchant.business_name %></dd>

  <dt>Rfp</dt>
  <dd><%= @offer.rfp.full_diamond_trait %></dd>

</dl>