config/routes.rb
Diamond::Application.routes.draw do
  devise_for :users
  root "rfps#new"

  get '/matches/new', controller: 'matches', action: 'new', as: 'new_match'
  post '/matches', controller: 'matches', action: 'create', as: 'matches'

  get '/matches', controller: 'matches', action: 'index'
  get '/matches/:id', controller: 'matches', action: 'show', as: 'match'

  get '/matches/:id/edit', controller: 'matches', action: 'edit', as: 'edit_match'
  patch '/matches/:id', controller: 'matches', action: 'update'

  delete '/matches/:id', controller: 'matches', action: 'destroy'

  get '/merchants/new', controller: 'merchants', action: 'new', as: 'new_merchant'
  post '/merchants', controller: 'merchants', action: 'create', as: 'merchants'

  get '/merchants', controller: 'merchants', action: 'index'
  get '/merchants/:id', controller: 'merchants', action: 'show', as: 'merchant'

  get '/merchants/:id/edit', controller: 'merchants', action: 'edit', as: 'edit_merchant'
  patch '/merchants/:id', controller: 'merchants', action: 'update'

  delete '/merchants/:id', controller: 'merchants', action: 'destroy'

  get '/users/new', controller: 'users', action: 'new', as: 'new_user'
  post '/users', controller: 'users', action: 'create', as: 'users'

  get '/users', controller: 'users', action: 'index'
  get '/users/:id', controller: 'users', action: 'show', as: 'user'

  get '/users/:id/edit', controller: 'users', action: 'edit', as: 'edit_user'
  patch '/users/:id', controller: 'users', action: 'update'

  delete '/users/:id', controller: 'users', action: 'destroy'

  get '/offers/new', controller: 'offers', action: 'new', as: 'new_offer'
  post '/offers', controller: 'offers', action: 'create', as: 'offers'

  get '/offers', controller: 'offers', action: 'index'
  get '/offers/:id', controller: 'offers', action: 'show', as: 'offer'

  get '/offers/:id/edit', controller: 'offers', action: 'edit', as: 'edit_offer'
  patch '/offers/:id', controller: 'offers', action: 'update'

  delete '/offers/:id', controller: 'offers', action: 'destroy'

  get '/rfps/new', controller: 'rfps', action: 'new', as: 'new_rfp'
  post '/rfps', controller: 'rfps', action: 'create', as: 'rfps'

  get '/rfps', controller: 'rfps', action: 'index'
  get '/rfps/:id', controller: 'rfps', action: 'show', as: 'rfp'

  get '/rfps/:id/edit', controller: 'rfps', action: 'edit', as: 'edit_rfp'
  patch '/rfps/:id', controller: 'rfps', action: 'update'

  delete '/rfps/:id', controller: 'rfps', action: 'destroy'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Diamond</title>

  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootswatch/3.0.2/cerulean/bootstrap.min.css">
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.0.2/css/font-awesome.min.css">

  <style>
    /* Only necessary if you are using navbar-fixed-top */
    body {
      padding-top: 50px;
    }
  </style>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to Rails.application.class.parent_name, root_url, :class => "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Requests For Proposal", rfps_url %></li>
        <li><%= link_to "Offers", offers_url %></li>
        <li><%= link_to "Merchants", merchants_url %></li>
        <li><%= link_to "Matches", matches_url %></li>
        <li><%= link_to "Users", users_url %></li>
        <% if user_signed_in? %>
          <li><%= link_to current_user.email, edit_user_url(current_user.id) %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </nav>

  <div class="container">
    <% if notice.present? %>
      <div class="alert alert-dismissable alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= notice %>
      </div>
    <% end %>

    <% if alert.present? %>
      <div class="alert alert-dismissable alert-warning">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= alert %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>